### ISSUE TITLE
Is it possible to fetch an instance of model object ?

### ISSUE THREAD

**Issue by Redigast13** [sagarrabadiya/ng2-resource#3]
Hello! I need to get an instance of model when I execute RestResource query() method. Is it possible to set some function that will transform data from server to model objects?
For example:

```
this.usersDataProvider.query({}).$observables.subscribe(users => {
    // users is array of instances of UserModel class 
});
```

**Comment by sagarrabadiya** [comment]
@Redigast13 for now this is not, directly supported, i will add that support, but for now, you can create some sort of function in you data provider and that will return the transformed array, so instead of calling query method in controller use some transformed method

for ex.

in your usersDataProvider class

```
transformed() {
   var observableInstance = this.query({}).$observables;
   observableInstance.subscribe(users => {
        return this.transform(users); // this function is defined inside class itself
    });
    return observableInstance;
}

//then in controller
this.usersDataProvider.transformed().subscribe(users=>{
// userModel instances array
});
```

or return some custom observable and complete it when transformation is done. the above is not tested code, but it can do something like it.

**Comment by Redigast13** [comment]
@sagarrabadiya thank you!
